### ISSUE TITLE
microscope occasinally plots garbage

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/microscope#11]
I did the following on 687horton:
1. Run `dastard`
2. Run `dc.py`
3. Set a TriangleSource with 8 channel, 100000 samples/second, triangle maximum 1, triangle minimum 0.
4. Set Auto Trigger to  0 ms on All Channels. 15000 samples/record, 3750 presamples
5. Open Microscope, select first 8 fb channels.
6. Observe microscope, note that sometimes it appear the last value in the plot is greater than 10000.

To isolate the problem to microscope I did the following tests:
1. Change the trigger condition to a rising edge with 2 raw threshold. The trigger rate is zero.
2. Change the trigger condition to a level trigger with 2 raw threshold. The trigger rate is zero.
3. Run the script at this link: https://gist.github.com/ggggggggg/8402d3d6acef408110c6715f78d35ca9, the script reads published records and checks for values >1, I found no values>1 in 1000 records.
4. Add a print statement in the auto and edge triggering code that prints if any value in `raw` is greater than 1. I saw none of these statements.

I didn't see this happening on my mac, though I was some other problems, so I'm not totally sure about that.

**Comment by ggggggggg** [comment]
if this goes away with newer versions of dastard, it might be related to the data rate from the source not being fixed before.

**Comment by joefowler** [comment]
Were you sitting in the lab? So, that is, both dastard and microscope were both on a linux machine?

I could not reproduce your problems on my Mac. This is, of course, with recent versions of everything.

We should probably consider a policy that triangles of small but nonzero size should have multiple cycles put into the pre-computed buffer.

**Comment by ggggggggg** [comment]
Yes I was in the lab, dastard and microscope both on same machine.

I did make the triangle high=triangle low case have a buffer sized for 1/10th of a second. The same could be done for triangles of short duration. But probably microscope still shouldn't be capable of plotting garbage.

**Comment by joefowler** [comment]
I think this is gone as of July 10 or 11. There seems to be a hard crash that can happen in the latest versions of microscope and dastard, but I'll have to track that down and make it a separate issue.
