### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/microscope#26]
I left microscope running for for many (3+) days, and the computer was super slow when I came back. I checked top and microscope was using 69% of the memory. I restarted it and it was at 0.4%, after about 5 mins it read 0.5%, and after 10 mins it read 0.6%.

I was using dastard to stream triangles from a lancero card at 160 MB/s, and averaging traces.

**Comment by ggggggggg** [comment]
DASTARD was crashing on the RAVEN pc, and it was due to microscope using up 80% of the memory due to this leak.

**Comment by joefowler** [comment]
One definite source of unbounded memory use is that the "analyzed values" (baseline, plus pulse max, mean, and RMS) are stored in a `QVector` that gets cleared under only under certain circumstances. If not cleared, then they are allowed to `QVector::append` on the end indefinitely. That vector grows when analysis is being plotted, obviously, but I think it also grows when pulses are being plotted (for no good reason).

Plan: implement "hard" and "soft" limits on their size. Say, 11k and 10k. When they are at the hard limit and it's time to add another value, remove the oldest 1k values to reach the soft limit size. Ideally, these limits would be user-settable.

But I don't know how to check for other memory leaks, and I suspect there are some. The tool `valgrind` does not run on Mac OS X Mojave (at least, not the Macports version). I guess we can try on a Linux machine.
