### ISSUE TITLE
Microscope needs to handle non-consecutive channel numbers

### ISSUE THREAD

**Issue by joefowler** [usnistgov/microscope#33]
I'm not sure how to do this, but microscope needs some way to handle non-consecutive channel numbering, as it now exists in Dastard.

How it works now: microscope takes mandatory command-line arguments `-r28 -c8` to signal row * column geometry. That makes sense for TDM systems with one card, but even TDM is going to expand the way of numbering channels (see [Dastard issue 212](https://github.com/usnistgov/dastard/issues/212)).

Microscope's main data flow consists of messages, one per triggered record. These messages don't say anything about the channel numbering system, but only give the channel number of _this_ record as an int16. (Or uint16?)

Possible solutions:
1. Add the full channel information to the header of each message (each triggered record).
1. Send a new kind of message regularly (every few seconds), with the full channel numbering information.
1. Make the full channel numbering information part of a command-line argument.
1. Store a file in some standard place (maybe `~/.dastard/channels.yaml`) with the full channel numbering information.

What is "full channel information"? It's:
* How many channel groups there are.
* Two facts for each group: the number of channels and the first channel's number.

That is an unwieldy amount to enter and parse as a command-line argument, even if it's usually generated by code. It's possible to add it to a message header, but it seems silly to send this same info over and over and over and over. Also, redefining the message header, or defining a new message both seem kind of painful.

I favor the configuration file approach. An important drawback would be that it's an unwanted extra step to get that config file onto another computer to run microscope remotely. I don't really see this as a big problem. How often does that come up? We could include a command-line argument `--index` to say that channels should be numbered consecutively from 0 (by their channel _index_) instead of reading the configuration file. That would make it possible to plot _something_, quickly from a remote computer. Or, if this becomes an actual thing, we can start with the YAML file idea, then also add the new kind of message idea.

**Comment by ggggggggg** [comment]
4 seems good enough for now

**Comment by joefowler** [comment]
Can probably use [yaml-cpp](https://github.com/jbeder/yaml-cpp) (or see [examples](https://codedocs.xyz/jbeder/yaml-cpp/md_docs_Tutorial.html)) for parsing YAML in Microscope. I'll plan on the file idea.

**Comment by joefowler** [comment]
Or if we use JSON, see this supposedly "tiny" [JSON for C++11](https://github.com/dropbox/json11). And as @ggggggggg points out, Golang is already more oriented to JSON than to YAML.

**Comment by joefowler** [comment]
If YAML, consider [mini-yaml](https://github.com/jimmiebergmann/mini-yaml), a "single header YAML 1.0 C++11 serializer/deserializer."

**Comment by joefowler** [comment]
Fixed in PR #36.
