### ISSUE TITLE
problems with lancero and "groups" in dastard

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/microscope#38]
From Horton, set up with 8x8 tdm.

1. Microscope has error and fb switched.
2. All items in quick switcher list group 0.
3. Microscope thinks there are 128 fb channels. (64 is correct)

**Comment by ggggggggg** [comment]
Issues 2 and three have been resolved, but issues 1 remains, feedback and error are swapped in microscope. Oddly the error vs feedback plots gets them right while the plots you get from using the quick select drop downs are switched.

**Comment by joefowler** [comment]
That's super weird. On the other hand, it also sounds quite easy to fix. I'll look into it.
